# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven build pipeline

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - develop
        - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Abort Previous Builds
        uses: potiuk/cancel-workflow-runs@v4_8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cancelMode: duplicates

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Build and Test
        run: |
          mvn -B -U clean verify
